### ISSUE TITLE
краш при некорректном вводе

### ISSUE THREAD

**Issue by Pixta4ok** [JetBaget/Calculator#10]
$ python calc.py
1 + + +
Traceback (most recent call last):
  File "calc.py", line 86, in <module>
    res += int(o_perands.dequeue())
ValueError: invalid literal for int() with base 10: ''

**Comment by Pixta4ok** [comment]
$ echo "1+2-" | python calc.py > res.txt
Traceback (most recent call last):
  File "calc.py", line 89, in <module>
    res -= int(o_perands.dequeue())
ValueError: invalid literal for int() with base 10: ''
